---

- name: Create the cAdvisor docker container
  docker_container:
    name: google-cadvisor
    image: google/cadvisor:latest
    state: present
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
    restart_policy: always
  tags:
    docker-services
